name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  # Tillader at køre dette workflow manuelt fra Actions fanen
  workflow_dispatch:

# Sæt nødvendige tilladelser for GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Tillad kun én concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: CatalyticFuzion/package-lock.json
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Install dependencies
        run: cd CatalyticFuzion && npm ci
      
      - name: Build website
        run: cd CatalyticFuzion && npm run build
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: CatalyticFuzion/build

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
