name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:

# Set required permissions for GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Check file structure
        run: ls -la
      
      - name: Install dependencies (clean install)
        run: npm install
        
      - name: Remove i18n directory if exists
        run: rm -rf i18n || true
        
      - name: Remove blog directory if exists
        run: |
          rm -rf blog || true
          # Remove any custom blog components
          find src/theme -name "*Blog*" -type f -delete || true
          find src -name "*blog*" -type d -exec rm -rf {} + || true
          find src -type f -name "*.tsx" -o -name "*.ts" -o -name "*.js" -o -name "*.jsx" | xargs grep -l "@theme/Blog" | xargs rm -f || true
      
      - name: List docs directory before build
        run: ls -la docs/
        
      - name: Check HomepageFeatures component
        run: |
          if [ -f "src/components/HomepageFeatures/index.js" ]; then
            echo "HomepageFeatures/index.js exists:"
            cat "src/components/HomepageFeatures/index.js"
          elif [ -f "src/components/HomepageFeatures/index.tsx" ]; then
            echo "HomepageFeatures/index.tsx exists:"
            cat "src/components/HomepageFeatures/index.tsx"
          else
            echo "HomepageFeatures component not found in expected locations."
            find src -name "*.js" -o -name "*.tsx" | grep -i homepage
          fi
          
      - name: Find blog-related TypeScript files
        run: |
          echo "Finding blog-related files..."
          find src -type f -name "*.tsx" -o -name "*.ts" -o -name "*.js" -o -name "*.jsx" | xargs grep -l "blog" || true
          find . -name "*Blog*" -type f | grep -v "node_modules" || true
        
      - name: Build website
        run: npm run build || npm run build -- --no-minify
        
      - name: Show build errors if any
        if: failure()
        run: cat .docusaurus/build.errors.log || echo "No error log found"
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
