name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:

# Set required permissions for GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Create static HTML site
        run: |
          # Backup existing content
          mkdir -p _backup
          cp -r docs _backup/ || true
          cp README.md _backup/ || true
          
          # Clean slate approach - create a minimal static site
          rm -rf docs blog src static .docusaurus build || true
          mkdir -p build
          
          # Create a simple index.html
          cat > build/index.html << 'EOF'
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>CatalyticFuzion</title>
            <style>
              body {
                font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
                line-height: 1.6;
                color: #333;
                max-width: 800px;
                margin: 0 auto;
                padding: 20px;
              }
              h1, h2, h3 { 
                color: #2e6c99;
              }
              a {
                color: #0366d6;
                text-decoration: none;
              }
              a:hover {
                text-decoration: underline;
              }
              .container {
                margin-top: 40px;
              }
              .footer {
                margin-top: 40px;
                padding-top: 20px;
                border-top: 1px solid #eaecef;
                color: #586069;
                font-size: 0.9em;
              }
            </style>
          </head>
          <body>
            <div class="container">
              <h1>CatalyticFuzion</h1>
              <p>CatalyticFuzion is an innovative project aimed at creating a Human-to-AI Domain Specific Language (DSL) by building on concepts from <a href="https://cucumber.io/docs/gherkin/">Gherkin</a> and object-oriented programming paradigms.</p>
              
              <h2>Vision</h2>
              <p>The project originally started as "GherkinSharp," inspired by the Behavior-Driven Development (BDD) paradigm, but has evolved into CatalyticFuzion as we move beyond traditional BDD constraints toward a more flexible and powerful human-AI interface.</p>
              
              <p>Our goal is to create a DSL that:</p>
              <ul>
                <li>Makes it easier for humans to communicate complex concepts to AI systems</li>
                <li>Leverages the best of both Gherkin's readable syntax and object-oriented programming</li>
                <li>Acts as a catalyst for effective human-AI collaboration</li>
              </ul>
              
              <h2>Resources</h2>
              <ul>
                <li><a href="https://github.com/catalyticfuzion/catalyticfuzion.github.io">GitHub Repository</a></li>
                <li><a href="https://cucumber.io/docs/gherkin/">Gherkin Reference</a></li>
              </ul>
              
              <div class="footer">
                <p>© $(date +%Y) CatalyticFuzion. All rights reserved.</p>
                <p>Created by <a href="https://github.com/catalyticfuzion">TwistedBrain</a></p>
              </div>
            </div>
          </body>
          </html>
          EOF
          
          # Add a simple 404 page
          cp build/index.html build/404.html
          
          echo "Created minimal static site"
          ls -la build/
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
